maintitle: Development Team Documentation Theme
title: Intuitive Systems Documentation Theme
email: support@intuitivesystems.co.uk
description: 
baseurl: "/DocumentationSiteThemes"
url: "http://intuitivedocs.github.io/DocumentationSiteThemes/"
fixedNav: 'false'
theme: grey
contentsref: "/DocumentationSiteThemes/content/" 
styleurl: "/DocumentationSiteThemes"
fullstyleurl: "http://intuitivedocs.github.io/DocumentationSiteThemes"

# collections
collections:
     content:
        output: true

defaults:
-
  scope:
    path: ""
    type: "content"
  values:
    layout: "post"


# Build settings
permalink: :title.html
markdown: kramdown
include: [_pages,categories]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

